import score

motif = ['ATATTTGCA', 'ATATTTGTT', 'AGCTCCGCA', 'GCGTTTTTA', 'ATAATTTTA', 'GGCTCAGCC', 'AGGCTCTCA', 'CGCTTGGTC', 'CTCGCCGCT', 'ATCTGCTTA', 'ATCCGTTTC', 'AGCATGGTG', 'ATCACCATG', 'ATCCCTCTG', 'CTCCGGCTT', 'ATCCGGCTT', 'ATCCGTTTG', 'ATCTCGCTG', 'ATAATCGCA', 'ATCCCAGCA', 'ATCCCCATA', 'TTCTGCTCT', 'TGACGCGTG', 'AGCTGGCCA', 'AGCTCCCGG', 'ATCCGGGAG', 'AGCCAGCGA', 'ATCGCTGGC', 'ATCGCGGGA', 'ATCCCGCGA', 'AGCTGCAGA', 'ATAATCTGC', 'AGAAGTTAA', 'ATCAGGCTA', 'AAAGGGTTA', 'AGACGCCAC']

score.PWMScore(motif)
